# Generated by Django 4.0.1 on 2022-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('headquarters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.ManyToManyField(to='timetables.Days')),
                ('head_quarter', models.ManyToManyField(blank=True, related_name='sede', to='headquarters.HeadQuarter')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
