# Generated by Django 4.0.1 on 2022-01-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('headquarters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('head_quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sede', to='headquarters.headquarter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_time', to='users.account')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
