# Generated by Django 4.0.1 on 2022-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'ordering': ('-day',)},
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=8),
        ),
    ]
