# Generated by Django 4.0.1 on 2022-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0004_remove_headquarter_time_tables_and_more'),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='head_quarter',
        ),
        migrations.AddField(
            model_name='timetable',
            name='head_quarter',
            field=models.ManyToManyField(related_name='sede', to='headquarters.HeadQuarter'),
        ),
    ]
