# Generated by Django 4.0.1 on 2022-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_alter_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
