# Generated by Django 4.0.1 on 2022-01-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('headquarters', '0001_initial'),
        ('timetables', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='headquarter',
            name='time_tables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='timetables.timetable'),
        ),
    ]
