# Generated by Django 4.0.1 on 2022-01-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0001_initial'),
        ('headquarters', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headquarter', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='headquarter',
            name='time_tables',
            field=models.ManyToManyField(blank=True, related_name='horarios', to='timetables.TimeTable'),
        ),
    ]
