# Generated by Django 4.0.1 on 2022-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarter',
            name='state',
            field=models.CharField(choices=[('On', 'Activo'), ('Of', 'Inactivo')], default='On', max_length=2),
        ),
    ]
