# Generated by Django 4.0.1 on 2022-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0004_remove_headquarter_time_tables_and_more'),
        ('timetables', '0002_remove_timetable_user_remove_timetable_head_quarter_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='headquarter',
            field=models.ManyToManyField(related_name='headquarters', to='headquarters.HeadQuarter'),
        ),
        migrations.AddField(
            model_name='account',
            name='timetables',
            field=models.ManyToManyField(related_name='timetables', to='timetables.TimeTable'),
        ),
    ]
